notifications:
  email: false
language: cpp
os:
  - windows
  - osx
script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then ./run_win.bat; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./run_osx.sh; fi

deploy:
  provider: releases
  prerelease: true
  api_key:
    secure: korGa/fjH9Ky+6wAd4Tm5ysPmjHRm/UsXPnPaTPiEhqCNGMYAWQJShtYUP11MHBHDm2yhFJ06TXA5eMfLJHXCVj1aJv8PKcB/okU8Bu3DgG1HYqkX1XvFGIwHF5xwI7dz8VX3bvPCe/AxvmbnVUrfL3N9RuOjhw82acwuXnka3KHLYeIcJFXF7xSFIcv4f29Mv7woHQyhF+PRC4KbHS6l+gYhig7vFiDykf1a1cglbWLRsqMmujqKGrQMc/HPYNl8KueuHFmk2wgS8N821PmRdQtPX1nltSKgPMj4iX6QQwS/qTaOhwlqVLyliyJ9noiP/GmbDMB9CKIXZ5HZYRBilWWokEKtXEjpBZpOjbuo0kKtPh/W/YUHUhlI0KnUunb1aE+b50AgLKFVeOxon1PeVn4aJpreSm+RxkbWVd9pWjfyHEn3y2OXKFIUClQTczmpVhKWkU9C1AjveoBo6jmplcxfJ0/Kukz++5voTMe8nK0ITKLYNsuK4667c3IE2/33+uMbe6ES6edBT7ij01TdwyezprRTpx0G1y7xWJHp6wPluKo1aEKWRzCorrVnLBiRuBs/iFmpBlFufF4N07ry1rELZFY8LNxaj2BkMxq4VXwiO22w24NvYw7BPaSPIBtYeNsTRju3XzXVTQ/FhjPifQKZ+ShwvYCXPlqfqK8gZc=
  file:
    - mac.zip
    - windows.zip
  skip_cleanup: true
  on:
    tags: true
  overwrite: true

